apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: control
  template:
    metadata:
      labels:
        app: control
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube
      containers:
      - name: control
        image: control-plane:v1
